id: ICC54DC96
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:00:20+00:00'
last_modified: '2022-06-08T01:12:29.069981+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28876
  title: སྙན་རྩོམ་གཟི་མིག་དགུ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    2B75:
      image_group_id: I4860
      title: ''
      total_pages: 162
      order: 1
      base_file: 2B75.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
